#!/bin/sh
cd ${0%/*} || exit 1                        # Run from this directory
. $WM_PROJECT_DIR/bin/tools/RunFunctions    # Tutorial run functions

# An extruded mesh around cylinder
(cd sphereMesh && ./Allclean)

# The background mesh
(cd sphereAndBackground && ./Allclean)
